{% set name = "multiwebcam" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multiwebcam-{{ version }}.tar.gz
  sha256: b9ada8a298f7a6d5d88b164560018c056c71e5b6876a7f88c1b64ec909ef0542

build:
  entry_points:
    - mwc = multiwebcam.__main__:CLI_parser
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - poetry-core
    - pip
  run:
    - python >=3.10,<3.13
    - pyside6 >=6.6.1,<7.0.0
    - opencv >=4.8.1,<5.0.0
    - rtoml >=0.9.0,<0.10.0
    - pandas >=2.1.4,<3.0.0

test:
  imports:
    - multiwebcam
  commands:
    - mwc --help
  requires:
    - pip

about:
  home: https://github.com/mprib/multiwebcam
  summary: Record synchronized webcam footage
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
